In [2]:
import numpy as np
from sklearn import *
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pickle
from joblib import dump, load

from sklearn.datasets import load_boston
from sklearn.ensemble import RandomForestClassifier

from sklearn.tree import export_graphviz

# load data 
training_data = np.genfromtxt('/Users/saravill/Downloads/TrainingDataset.arff', delimiter=',', dtype=np.int32)

inputs = training_data[:,:-1]
print (inputs)

outputs= training_data[:, -1]
print (outputs)

# split test data and train data

training_inputs = inputs[:1250]
training_outputs = outputs[:1250] 

testing_inputs = inputs[1250:]
testing_outputs = outputs[1250:]

"""

@relation phishing

@attribute having_IP_Address  { -1,1 }    
@attribute URL_Length   { 1,0,-1 }
@attribute Shortining_Service { 1,-1 }
@attribute having_At_Symbol   { 1,-1 }
@attribute double_slash_redirecting { -1,1 }
@attribute Prefix_Suffix  { -1,1 }
@attribute having_Sub_Domain  { -1,0,1 }
@attribute SSLfinal_State  { -1,1,0 }      
@attribute Domain_registeration_length { -1,1 }
@attribute Favicon { 1,-1 }
@attribute port { 1,-1 }
@attribute HTTPS_token { -1,1 }
@attribute Request_URL  { 1,-1 }
@attribute URL_of_Anchor { -1,0,1 }
@attribute Links_in_tags { 1,-1,0 }
@attribute SFH  { -1,1,0 }
@attribute Submitting_to_email { -1,1 }
@attribute Abnormal_URL { -1,1 }
@attribute Redirect  { 0,1 }
@attribute on_mouseover  { 1,-1 }
@attribute RightClick  { 1,-1 }
@attribute popUpWidnow  { 1,-1 }
@attribute Iframe { 1,-1 }
@attribute age_of_domain  { -1,1 }
@attribute DNSRecord   { -1,1 }
@attribute web_traffic  { -1,0,1 }
@attribute Page_Rank { -1,1 }
@attribute Google_Index { 1,-1 }
@attribute Links_pointing_to_page { 1,0,-1 }
@attribute Statistical_report { -1,1 }
@attribute Result  { -1,1 }

"""

#Load boston housing dataset as an example
rf = RandomForestClassifier(n_estimators=100, max_depth=20,
                             random_state=42)

rf.fit(training_inputs, training_outputs)

predictions1 = rf.predict(testing_inputs)
accu =accuracy_score(testing_outputs, predictions1)
print (accu)

"""
export_graphviz(rf, 
                out_file = "phishingaa.dot",
                rounded=True,
                filled=True,
                )


(graph,) = pydot.graph_from_dot_file('tree_from_forest.dot')
graph.write_png('tree_from_forest.png')


"""

##. SSLfinal_State   URL_of_Anchor   web_traffic 
print (rf.feature_importances_*100)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]]
[-1 -1 -1 ... -1 -1 -1]
0.9335033146353902
[ 0.25627286  0.78662747  0.41844276  0.14726802  0.31589467  3.69688207
  5.64180775 27.7242637   1.81978371  0.38692895  0.28570932  0.69589994
  2.00110803 22.273091    3.98096606  0.57744725  0.56945432  0.37148832
  0.24691316  0.3530761   0.12476598  0.54829399  0.28658698  4.17971105
  2.74070317 12.91817475  2.92700777  1.3737365   2.02532499  0.32636931]
