In [4]:
import numpy as np
from sklearn import *
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pickle
from joblib import dump, load

# load data 
training_data = np.genfromtxt('/Users/saravill/Downloads/TrainingDataset.arff', delimiter=',', dtype=np.int32)

inputs = training_data[:,:-1]
print (inputs)

outputs= training_data[:, -1]
print (outputs)

# split test data and train data

training_inputs = inputs[:1250]
training_outputs = outputs[:1250] 

testing_inputs = inputs[1250:]
testing_outputs = outputs[1250:]

# use SVM Classifier

classifier = svm.SVC()
classifier.fit(training_inputs, training_outputs)


# persist the model in pickle or joblib to a file on the disc.  
#store = pickle.dumps(classifier)
dump(classifier, 'phishing.joblib') 

# predict the last 1000+ reocrds 

#clissfy = pickle.loads(store)  or load from the file system
clissfy = load('phishing.joblib') 

predictions = clissfy.predict(testing_inputs)

accu =accuracy_score(testing_outputs, predictions)
print (accu)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]]
[-1 -1 -1 ... -1 -1 -1]
0.9036206017338093


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/svm/base.py:189: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  warnings.warn("The default value of gamma will change "
